### PR TITLE
Load remote notes. Display & filter by labels.

### LINKED ISSUE #76: Importing notes - improvements
Importing notes works correctly but 3 things can be improved:
- it would be nice to limit files only to `*.json`
- when selected file is incorrect (for example pdf or incorrect json) it would be nice to have a proper message (currently we show that we found 0 notes in the file)
- if the file doesn't have any notes it does not make any sense to ask if it should override the current notes

### PR DESCRIPTION
**Pull request by tomusdrw**
This PR reworks a bit the internal model for storing notes. It's required to support features outlined in #83 

1. On top of that I've implemented displaying and filtering by labels (no user-defined labels yet).
2. Importing notes is not overwritting the existing ones (Closes #76)
3. Editing the node is re-worked (no more `onBlur`)
4. We have the ability to load remote notes from URL (see `remoteNotesSources`; no UI to edit it yet)

I don't want to add much more to this PR to make it easier to review. So far the changes should mostly only affect how notes are displayed. The only new feature visible at once is filtering by labels (but the user will only see one label: "local").

### CODE REVIEW

File: src/components/NotesProvider/NotesProvider.tsx [hunk 1]
```diff
@@ -95,122 +160,268 @@ function loadLegacyFromLocalStorage(): string | null {
...
+  const migrateNotes = useNotesMigration();
+  const remoteNotesMigrated = useRemoteNotes(migrateNotes, currentVersion);
 
-  useEffect(() => {
-    saveToLocalStorage(notes);
-  }, [notes]);
+  const updateLocalNotes = useCallback((localNotes: TAnyNote[]) => {
+    setHistory((history) => [...history, localNotes].slice(-1 * HISTORY_STEPS_LIMIT));
+    setLocalNotes(localNotes);
+    saveToLocalStorage(localNotes);
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:190]: please remove unnecessary data, such as `canMigrateTo` or `local/remote/imported` labels, before saving to local storage.

**Review by skoszuta — CHANGES_REQUESTED** [review]
Generally looks good. There are couple of things I'd like to point out though:
- It feels messy to save notes along with data that can be inferred in runtime, such as:
  - local/remote/imported labels (unless you'd drop the source property)
  - canMigrateTo: this one especially since it serves no purpose at all in local storage
- I feel like we should introduce note spec versioning. its a reasonable moment to do so because we can treat all notes without a spec property as v2. if we dont do this now were in for quite a mess on next iterations.

The rest is in the comments. Cheers

**Review by tomusdrw — COMMENTED** [review]
All points are pretty valid and should now be addressed.

Decided to change the note data model a bit. Cleaned it up from unnecessary stuff:
1. `pageNumber` was duplicated in `selectionStart`
2. `selectionString` was not really used and can be better deducted from the blocks (we don't need it as a safety measure any more imho).
3. Introduced an explicit container for notes (instead of storing just an array), since it avoid possible inconsistency in notes inside the array (what if I have a bunch of V2 and V3 notes mixed together in one array?) and I'm pretty sure it might come handy in the future when we need to attach more data there.

File: src/components/NotesProvider/NotesProvider.tsx [hunk 2]
```diff
@@ -57,160 +91,352 @@ function isINote(arg: unknown): arg is INote {
...
+
+      setLocalNotes(newNotes);
+      saveToLocalStorage(newNotes);
+      setHistory([...history]);
+    }, [history]),
+    handleImport: useCallback(
+      (jsonStr: string, label: string) => {
+        let newNotes = [];
+        try {
+          newNotes = parseNotesFromJson(jsonStr, `${LABEL_IMPORTED}${label}`).notes;
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:271]: If i understand correctly, imported v3 notes will never receive the "Imported" label

File: src/components/NotesProvider/NotesProvider.tsx [hunk 3]
```diff
@@ -1,52 +1,86 @@
...
 
-export interface INote {
+export type Label = {
+  label: string;
+  isActive: boolean;
+};
+
+export enum NoteSource {
+  Local = 0,
+  Imported = 1,
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:40]: `NoteSource.Imported` is never used anywhere

File: src/components/NotesProvider/NotesProvider.tsx [hunk 4]
```diff
@@ -57,160 +91,352 @@ function isINote(arg: unknown): arg is INote {
...
-      throw new Error("Invalid note format.");
+    // V2
+    if (Array.isArray(parsed)) {
+      if (parsed.every(isINoteV2)) {
+        return {
+          version: 3,
+          notes: parsed.map((note) => convertNoteV2toV3(note, defaultLabel)),
+        };
+      }
+      throw new Error("Notes JSON should be an array.");
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:130]: This `throw` breaks v2 imports

File: src/components/NotesProvider/NotesProvider.tsx [hunk 5]
```diff
@@ -57,160 +91,352 @@ function isINote(arg: unknown): arg is INote {
...
+      },
+      [localNotes, updateLocalNotes],
+    ),
     handleExport() {
-      const strNotes = JSON.stringify(notes);
-      const link = document.createElement("a");
-      link.setAttribute("href", `data:application/json;charset=utf-8,${encodeURIComponent(strNotes)}`);
-      link.setAttribute("download", `graypaper-notes-${new Date().toISOString()}.json`);
-      link.click();
+      const strNotes = JSON.stringify(localNotes);
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:284]: You export the `localNotes` array without the wrapper therefore they're always treated as V2 when importing.

File: src/components/NotesProvider/NotesProvider.tsx [hunk 6]
```diff
@@ -57,160 +91,352 @@ function isINote(arg: unknown): arg is INote {
...
+              version,
+              selectionStart,
+              selectionEnd,
+            };
+          }
+
+          const newSelection = await migrateSelection({ selectionStart, selectionEnd }, version, currentVersion);
+
+          if (!newSelection) {
+            return {
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:408]: this is the exact same return as in line 394. Please merge them

File: src/components/NotesProvider/NotesProvider.tsx [hunk 7]
```diff
@@ -57,160 +91,352 @@ function isINote(arg: unknown): arg is INote {
...
+function useNotesMigration() {
+  const { migrateSelection } = useContext(CodeSyncContext) as ICodeSyncContext;
+  const migrateNotes = useCallback(
+    (notes: INoteV3[], source: NoteSource, currentVersion: string) => {
+      return Promise.all(
+        notes.map(async (note): Promise<INote> => {
+          // TODO [ToDr] We can potentially cache that by re-using the migrations
+          // that were already done.
+          const { version, selectionStart, selectionEnd } = note;
+          const hash = await xxhash32(`${source}-${note.version}-${note.date}-${note.content}`);
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:392]: i do believe the hash lib is an overkill since you can simply use that string (or any simple hash doable in js) as key for react components. up to you though, its fun to have nice hashes

File: src/components/NotesProvider/NotesProvider.tsx [hunk 8]
```diff
@@ -1,52 +1,86 @@
...
 
-export interface IHighlightNote extends INote, ISelectionParams {
-  selectionString: string;
+interface INotesV3 {
+  version: 3;
+  notes: INoteV3[];
 }
 
-export type TAnyNote = IPointNote | IHighlightNote;
+export type INote = ISelectionParams & {
```
Comment (skoszuta) [inline src/components/NotesProvider/NotesProvider.tsx:69]: The naming here is a bit confusing. There's `INoteV2`, `INoteV3` and then `INote` which has an entirely different hierarchy of properties and serves a different purpose. It would be nice to indicate that:
- it's a decorated version of a raw note (you change naming the other way around, by changing INoteV2 or INoteV3 to something else)
- the selection params on this one are migrated/temporary.

**Review by skoszuta — CHANGES_REQUESTED** [review]
I agree with the goals you're going after but:
- import/export is broken
- some parts seem unfinished/untested/unclear
Details in the comments

As a general side note the code seems a little convoluted for what it does and NotesProvider grew kinda large. That's not a blocker but just my impression.

Cheers

File: src/components/NotesProvider/NotesProvider.tsx (hunk 2 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Yes.

File: src/components/NotesProvider/NotesProvider.tsx (hunk 3 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Removed

File: src/components/NotesProvider/NotesProvider.tsx (hunk 4 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Fixed.

File: src/components/NotesProvider/NotesProvider.tsx (hunk 5 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Fixed.

File: src/components/NotesProvider/NotesProvider.tsx (hunk 6 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Fixed.

File: src/components/NotesProvider/NotesProvider.tsx (hunk 7 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Removed.

File: src/components/NotesProvider/NotesProvider.tsx (hunk 8 above)
Comment (tomusdrw) [reply src/components/NotesProvider/NotesProvider.tsx]: Reworked.

**Comment by tomusdrw** [comment]
Reworked & refactored the code further.

- [ ] Extracted hooks from `NotesProvider`
- [ ] Moved local storage management and import/export functions to utils and added tests.

Let me know wdyt.

File: src/components/NotesProvider/NotesProvider.tsx [hunk 9]
```diff
@@ -95,122 +160,268 @@ function loadLegacyFromLocalStorage(): string | null {
...
+      for (const source of remoteNotesSources) {
+        try {
+          const data = await fetch(source);
+          const content = await data.text();
+          const notes = parseJson(content).map((note) => {
+            const n = convertNoteV2toV3(note, LABEL_REMOTE) as TAnyNote;
+            n.source = NoteSource.Remote;
+            return n;
+          });
+          remoteNotes.push(...notes);
```
[the remark this answers is not in the document]
Comment (skoszuta) [reply src/components/NotesProvider/NotesProvider.tsx]: indeed there isn't a biome rule for it. it looks like the lead maintainer has an opinion on this topic: https://github.com/biomejs/biome/discussions/3#discussioncomment-7379356

**Review by skoszuta — APPROVED** [review]
Looking good! Nice call with adding the tests.

One thing i noticed is that when a note fails automatic migration we show it to the user without an ability to migrate it manually. If that wasn't intentional that's the only thing I'd consider fixing.

Other than that lgtm 🚀

**Comment by tomusdrw** [comment]
> Looking good! Nice call with adding the tests.
> 
> One thing i noticed is that when a note fails automatic migration we show it to the user without an ability to migrate it manually. If that wasn't intentional that's the only thing I'd consider fixing.
> 
> Other than that lgtm 🚀

Good catch, fixed, thanks!
